--------------------------------------------------------
--  DDL for Table DW_DATE
--------------------------------------------------------

  CREATE TABLE "BDII_1702033"."DW_DATE" 
   (	"DATEID" NUMBER, 
	"DATEFORMAT" DATE, 
	"DAYDW" NUMBER(2,0), 
	"MONTHDW" NUMBER(2,0), 
	"YEARDW" NUMBER(4,0), 
	"DAYWEEK" NUMBER(1,0), 
	"DAYOFWEEK" VARCHAR2(30 BYTE), 
	"DAYOFYEAR" NUMBER(3,0), 
	"WEEKEND" VARCHAR2(3 BYTE), 
	"WEEKOFYEAR" NUMBER(2,0), 
	"WEEKOFTHEMONTH" NUMBER(1,0), 
	"MONTHNAME" VARCHAR2(20 BYTE), 
	"QUARTER" NUMBER(1,0), 
	"QUARTERNAME" VARCHAR2(30 BYTE), 
	"FIRSTQUARTER" DATE, 
	"LASTQUARTER" DATE, 
	"HOLIDAY" VARCHAR2(30 BYTE), 
	"AFTERNOON" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
